export const servicesData = [
    {
      id: 1,
      title: 'STRATEGIC CONSULTATION',
      subTitle: 'Growth Guaranteed',
      description: 'We care about your business and our recipe for success guarantees safe planning over discrete projections and results.',
      imageSrc: '/imagen1.webp',
    },
    {
      id: 2,
      title: 'GOOGLE-FACEBOOK SEARCH',
      subTitle: 'Everyone is there',
      description: 'Search Engine Optimization is the natural and scalable growth of brands and firms where GOOGLE owns +95% of search intent.',
      imageSrc: '/imagen2.webp',
    },
    {
      id: 3,
      title: 'MESSAGING & AUTOMATIONS',
      subTitle: 'Do more with less',
      description: 'Improve lead acquisition and conversion with state-of-the-art growth hacking techniques.',
      imageSrc: '/imagen3.webp',
    },
    {
      id: 4,
      title: 'LEAD THEM TO YOUR ECOSYSTEM',
      subTitle: 'Digitalize everything',
      description: 'Put your business where your customers are consuming content next to their Visas and Mastercards.',
      imageSrc: '/imagen4.webp',
    },
    {
      id: 5,
      title: 'PRECISE TIME AND KNOWLEDGE',
      subTitle: 'Corporate analysis',
      description: 'We accompany brands and firms throughout their digital transformation.',
      imageSrc: '/imagen5.webp',
    },
    {
      id: 6,
      title: 'LEAD GENERATION & CUSTOMER SERVICE',
      subTitle: 'Avoid looseness',
      description: 'Learn to catch all incoming leads and chase your sales nonstop.',
      imageSrc: '/imagen6.webp',
    },
    {
      id: 7,
      title: 'TRUSTED, SAFE & RELIABLE WEBPAGE',
      subTitle: '+10yrs of eCommerce expertise',
      description: 'An experienced team at your service always ready for new projects!',
      imageSrc: '/imagen7.webp',
    },
  ];